from __future__ import annotations
import tkinter as tk
from tkinter import BOTH,LEFT,X,BooleanVar,StringVar,ttk
class LauncherFieldUiFixMixin:
 def _apply_health(self,report):self.health=report;self._render_status_strip()
 def _style(self):
  super()._style();s=ttk.Style(self.root);s.configure("Audio.TCombobox",fieldbackground="#0f1b26",background="#223746",foreground="#f7fbfd",arrowcolor="#f7fbfd",borderwidth=1,relief="solid",padding=(9,7),font=("Segoe UI Semibold",10));s.map("Audio.TCombobox",fieldbackground=[("readonly","#0f1b26"),("disabled","#18232e")],foreground=[("readonly","#f7fbfd"),("disabled","#7d8b96")],selectbackground=[("readonly","#0f1b26")],selectforeground=[("readonly","#f7fbfd")])
 @staticmethod
 def _action_button(parent,text,command,*,primary=False,enabled=True):
  bg="#4ac6d7" if primary else "#1b2a36";fg="#031014" if primary else "#f0f5f8";ab="#6bd7e5" if primary else "#294052";b=tk.Button(parent,text=text,command=command,bg=bg,fg=fg,activebackground=ab,activeforeground=fg,disabledforeground="#7b8994",relief="flat",bd=0,padx=18,pady=10,font=("Segoe UI Semibold",9),cursor="hand2" if enabled else "arrow")
  if not enabled:b.configure(state="disabled",bg="#17222b")
  return b
 def _page_settings(self):
  language=StringVar(value=self.config.language);channel=StringVar(value=self.config.update_channel);autostart=BooleanVar(value=self.config.start_with_windows);minimize=BooleanVar(value=self.config.minimize_to_tray);ttk.Label(self.content,text="LAUNCHER SETTINGS",style="Section.TLabel").pack(anchor="w",pady=(0,10));form=ttk.Frame(self.content,style="Card.TFrame",padding=18);form.pack(fill=X);ttk.Label(form,text=self.t("settings.language"),style="CardText.TLabel").grid(row=0,column=0,sticky="w",pady=8);ttk.Combobox(form,values=("en","ru"),state="readonly",textvariable=language,width=18).grid(row=0,column=1,padx=16,sticky="w");ttk.Label(form,text=self.t("settings.update_channel"),style="CardText.TLabel").grid(row=1,column=0,sticky="w",pady=8);ttk.Combobox(form,values=("stable","beta","alpha"),state="readonly",textvariable=channel,width=18).grid(row=1,column=1,padx=16,sticky="w");ttk.Checkbutton(form,text=self.t("settings.start_windows"),variable=autostart).grid(row=2,column=0,columnspan=2,sticky="w",pady=8);ttk.Checkbutton(form,text=self.t("settings.minimize_tray"),variable=minimize).grid(row=3,column=0,columnspan=2,sticky="w",pady=8);ttk.Button(form,text="SAVE SETTINGS",style="Primary.TButton",command=lambda:self._save_settings(language.get(),channel.get(),autostart.get(),minimize.get())).grid(row=4,column=0,sticky="w",pady=(14,0));ttk.Separator(self.content,orient="horizontal").pack(fill=X,pady=(20,14));ttk.Label(self.content,text="AUDIO",style="Section.TLabel").pack(anchor="w");ttk.Label(self.content,text="Select the microphone and output used by ORION Core. Changes remain owned by Core after Launcher reconnects.",style="Muted.TLabel",wraplength=800,justify="left").pack(anchor="w",pady=(4,10))
  try:inputs,outputs,state=self._audio_snapshot()
  except RuntimeError as e:self._card(self.content,"AUDIO DEVICES",str(e),wrap=760).pack(fill=X);return
  sel=state.get("selection",{});im=self._device_display_map(inputs,"Windows Default");om=self._device_display_map(outputs,"Windows Default");ri={v:k for k,v in im.items()};ro={v:k for k,v in om.items()};iv=StringVar(value=ri.get(sel.get("input_device_id","default"),"Windows Default"));ov=StringVar(value=ro.get(sel.get("output_device_id","default"),"Windows Default"));box=ttk.Frame(self.content,style="Card.TFrame",padding=16);box.pack(fill=X);ttk.Label(box,text="MICROPHONE / INPUT",style="CardTitle.TLabel").pack(anchor="w");ttk.Combobox(box,textvariable=iv,values=tuple(im),state="readonly",style="Audio.TCombobox",width=70).pack(anchor="w",fill=X,pady=(6,12));ttk.Label(box,text="HEADPHONES / OUTPUT",style="CardTitle.TLabel").pack(anchor="w");ttk.Combobox(box,textvariable=ov,values=tuple(om),state="readonly",style="Audio.TCombobox",width=70).pack(anchor="w",fill=X,pady=(6,12));ttk.Label(box,text=f"Core: {state.get('message','Unknown')}",style="CardText.TLabel").pack(anchor="w");buttons=tk.Frame(box,bg="#111923");buttons.pack(fill=X,pady=(12,0));self._action_button(buttons,"APPLY TO CORE",lambda:self._apply_audio_selection(im[iv.get()],om[ov.get()]),primary=True).pack(side=LEFT,padx=(0,8));self._action_button(buttons,"REFRESH DEVICES",lambda:self.show_page("settings")).pack(side=LEFT,padx=(0,8));self._action_button(buttons,"OPEN TEST",lambda:self.show_page("test")).pack(side=LEFT)
 def _page_test(self):
  hero=ttk.Frame(self.content,style="CardAlt.TFrame",padding=18);hero.pack(fill=X);ttk.Label(hero,text="FUNCTIONAL VERIFICATION",style="CardAltTitle.TLabel").pack(anchor="w");ttk.Label(hero,text="TEST",style="Hero.TLabel").pack(anchor="w",pady=(5,2));ttk.Label(hero,text="Run focused checks without leaving Launcher.",style="HeroMuted.TLabel").pack(anchor="w");core_ok=self.core.healthy()
  try:inputs,outputs,state=self._audio_snapshot() if core_ok else ([],[],{});sel=state.get("selection",{});rin=state.get("resolved_input");rout=state.get("resolved_output");api=core_ok
  except RuntimeError:inputs,outputs,state,sel,rin,rout=[],[],{},{},None,None;api=False
  audio=ttk.Frame(self.content,style="Card.TFrame",padding=14);audio.pack(fill=X,pady=(12,10));ttk.Label(audio,text="CONVERSATIONAL AUDIO TEST",style="CardTitle.TLabel").pack(anchor="w");ttk.Label(audio,text='START AUDIO TEST: say “Привет, как дела?”  Expected Core reply: “Всё хорошо. Связь установлена.”',style="CardText.TLabel",wraplength=780,justify="left").pack(anchor="w",pady=(4,4));ttk.Label(audio,text="TEST MICROPHONE checks the selected microphone and reports the result. TEST OUTPUT plays a test sound/phrase through the selected output and reports the result.",style="Muted.TLabel",wraplength=780,justify="left").pack(anchor="w",pady=(0,9));row=tk.Frame(audio,bg="#111923");row.pack(fill=X);self._action_button(row,"START AUDIO TEST",self._run_conversational_audio_test,primary=True,enabled=core_ok and rin is not None and rout is not None).pack(side=LEFT,padx=(0,8));self._action_button(row,"TEST MICROPHONE",lambda:self._run_physical_audio_test("input",rin),enabled=rin is not None).pack(side=LEFT,padx=(0,8));self._action_button(row,"TEST OUTPUT",lambda:self._run_physical_audio_test("output",rout),enabled=rout is not None).pack(side=LEFT);checks=(("CORE","PASS — connected" if core_ok else "FAIL — not reachable"),("AUDIO DISCOVERY",f"PASS — {len(inputs)} input / {len(outputs)} output" if api else "FAIL — API unavailable"),("MICROPHONE",self._selection_text(sel.get("input_device_id","default"),rin)),("OUTPUT",self._selection_text(sel.get("output_device_id","default"),rout)));ttk.Label(self.content,text="CURRENT CHECKS",style="Section.TLabel").pack(anchor="w",pady=(4,6));cards=ttk.Frame(self.content,style="Orion.TFrame");cards.pack(fill=X)
  for i,(title,text) in enumerate(checks):self._card(cards,title,text,wrap=185).pack(side=LEFT,fill=BOTH,expand=True,padx=(0,7 if i<len(checks)-1 else 0))
