from __future__ import annotations

from typing import Any

AG2_SEED_VERSION = "3"

FAMILY_CAPABILITIES: dict[str, tuple[str, ...]] = {
    "DCS_WORLD_STATE": (
        "DCS_TELEMETRY",
        "FLIGHT_CONTEXT",
        "WORLD_MODEL",
        "MISSION_TRUTH",
        "AIRCRAFT_IDENTITY",
        "AIRCRAFT_KNOWLEDGE",
        "CALLSIGN",
        "COCKPIT_ASSISTANCE",
    ),
    "INTERACTION": (
        "NATURAL_CONVERSATION",
        "INFORMATIONAL_RESPONSE",
        "NATURAL_INFORMATIONAL_PRESENTATION",
        "LIVE_DCS_FACT_PRESENTATION",
        "MIXED_COMMUNICATION",
        "PROTECTED_OPERATIONAL_COMMUNICATION",
        "INTERACTION_ROUTING",
        "REASONING",
        "TOOL_CALLING",
        "PERSISTENT_STATE",
    ),
    "AI_SPEECH": (
        "YANDEX_REALTIME",
        "QWEN_REALTIME",
        "QWEN_PLANNER",
        "STT",
        "SPEECHKIT_STT",
        "TTS",
        "SPEECHKIT_TTS",
        "PRESENTATION",
        "VOICE_IDENTITY",
        "AUDIO_IO",
    ),
    "RADIO": (
        "SRS",
        "RADIO_ROUTER",
        "RADIO_ENTITY",
        "PTT",
        "EOU",
        "UDP7082",
        "RADIO_SCHEDULING",
    ),
    "COMMUNICATION": (
        "PHRASEOLOGY",
        "OSU",
        "COMMUNICATION_PROFILE",
        "LANGUAGE_POLICY",
    ),
    "ATC": (
        "VIRTUAL_ATC",
        "AIRPORT_ATC",
        "CARRIER_ATC",
        "GROUND",
        "TAXI",
        "TOWER",
        "TAKEOFF",
        "DEPARTURE",
        "ARRIVAL",
        "APPROACH",
        "LANDING",
        "GO_AROUND",
        "ATC_HANDOFF",
        "ATC_STATUS",
        "EMERGENCY",
    ),
    "MISSION_DOMAINS": (
        "AWACS_GCI",
        "AAR",
        "JTAC_FAC",
        "MISSION_CONTROL",
    ),
    "PRODUCT_DEVELOPMENT": (
        "PRODUCT_SCOPE",
        "LAUNCHER",
        "INSTALLER",
        "UNINSTALLER",
        "RUNTIME_MODULES",
        "LIFECYCLE",
        "PACKAGING",
        "EVIDENCE",
        "SECURITY",
        "CREDENTIALS",
        "DEBRIEF",
        "NEWS",
        "MISSION_EDITOR",
        "VR_OVERLAY",
        "GENERAL_VR_TUNING",
        "ARCHITECTURE_GOVERNANCE",
    ),
}

CAPABILITY_DETAILS: dict[str, dict[str, Any]] = {
    "AIRCRAFT_IDENTITY": {
        "description": "Present the current live-DCS aircraft identity without transferring fact authority to a language model.",
        "aliases": ["current aircraft", "aircraft identity query", "what aircraft am I in"],
        "historical_terms": ["FlightContext aircraft", "AIRCRAFT_IDENTITY_QUERY"],
        "code_symbols": ["AircraftIdentityQuery", "flight.current_aircraft_identity"],
        "related_domains": ["DCS", "WorldModel", "informational response"],
    },
    "NATURAL_INFORMATIONAL_PRESENTATION": {
        "description": "Natural AI formulation of informational answers from authoritative Core facts.",
        "aliases": ["natural response", "informational answer", "AI wording", "natural informational wording", "formulation"],
        "historical_terms": ["Realtime response", "FlightContext response", "aircraft informational response"],
        "code_symbols": ["NaturalInformationalPresentation"],
        "providers": ["Yandex Realtime", "Qwen Planner"],
        "related_domains": ["interaction", "DCS facts"],
    },
    "LIVE_DCS_FACT_PRESENTATION": {
        "description": "Present a fresh authoritative DCS/Core fact through an informational voice path.",
        "aliases": ["live telemetry answer", "DCS context response", "live DCS information"],
        "historical_terms": ["Stage 6A context injection", "FlightContext presentation"],
        "code_symbols": ["FlightContextService", "WorldModelFacade"],
    },
    "YANDEX_REALTIME": {
        "aliases": ["Yandex AI Studio Realtime", "Realtime", "persistent Realtime"],
        "historical_terms": ["Stage 6A realtime AI context"],
        "providers": ["Yandex"],
    },
    "QWEN_PLANNER": {
        "aliases": ["Qwen formulation", "PlannerProvider", "Yandex Qwen planner"],
        "code_symbols": ["YandexQwenPlannerProvider", "PlannerProvider"],
        "providers": ["Yandex AI Studio", "Qwen"],
    },
    "PTT": {
        "aliases": ["push to talk", "physical PTT", "radio transmit state"],
        "historical_terms": ["IsSending", "TX state"],
    },
    "EOU": {
        "aliases": ["end of utterance", "turn end", "transmission end", "radio EOU"],
        "historical_terms": ["packet gap", "quiescence", "explicit Eou"],
    },
    "UDP7082": {
        "aliases": ["SRS 7082", "IsSending true false", "SRS TX state"],
        "historical_terms": ["GameGUI UDP 7082", "authoritative TX end"],
    },
    "RADIO_SCHEDULING": {
        "aliases": ["TX pacing", "candidate buffering", "cadence-aware liveness"],
        "historical_terms": ["stale timeout", "radio turn lifecycle"],
    },
    "COMMUNICATION_PROFILE": {
        "aliases": ["aviation rules profile", "profile pack", "ICAO FAA NATO FAP"],
        "historical_terms": ["communication rules menu", "profile selector"],
        "code_symbols": ["CommunicationProfile", "CommunicationProfilePackStore"],
    },
    "LANGUAGE_POLICY": {
        "aliases": ["response language", "input language", "follow user language"],
        "historical_terms": ["FREE_RU", "FREE_EN", "AVIATION_RU", "AVIATION_EN", "hard language modes"],
    },
    "STT": {
        "aliases": ["speech recognition", "radio transcription", "voice input"],
        "historical_terms": ["Whisper", "SpeechKit RecognizeStreaming"],
    },
    "SPEECHKIT_STT": {
        "aliases": ["SpeechKit v3", "RecognizeStreaming", "external EOU STT"],
        "code_symbols": ["SpeechKitRadioSttAdapter"],
        "providers": ["Yandex SpeechKit"],
    },
    "PHRASEOLOGY": {
        "aliases": ["Pilot Phraseology KB", "aviation wording", "protected wording"],
        "historical_terms": ["20-30 phrase corpus", "Mixed Composition", "Hybrid D"],
    },
    "OSU": {
        "aliases": ["OperationalSemanticUnit", "protected operational semantic unit"],
        "code_symbols": ["OperationalSemanticUnit"],
    },
    "VIRTUAL_ATC": {
        "aliases": ["ATC", "Core ATC", "virtual controller"],
        "historical_terms": ["MODEL C ATC"],
    },
    "AWACS_GCI": {
        "aliases": ["AWACS", "GCI", "AWACS voice interaction"],
        "historical_terms": ["AWACS/GCI conversational route"],
    },
    "TAKEOFF": {
        "aliases": ["takeoff clearance", "pure takeoff", "departure clearance"],
        "historical_terms": ["Golden takeoff", "MODEL C takeoff"],
    },
    "ATC_STATUS": {
        "aliases": ["ATC_STATUS_QUERY", "status query", "what did you clear me for"],
        "code_symbols": ["AtcStatusQuery"],
    },
}

CAPABILITY_PARENTS: tuple[tuple[str, str], ...] = (
    ("INFORMATIONAL_RESPONSE", "NATURAL_INFORMATIONAL_PRESENTATION"),
    ("INFORMATIONAL_RESPONSE", "LIVE_DCS_FACT_PRESENTATION"),
    ("DCS_TELEMETRY", "FLIGHT_CONTEXT"),
    ("FLIGHT_CONTEXT", "AIRCRAFT_IDENTITY"),
    ("WORLD_MODEL", "AIRCRAFT_IDENTITY"),
    ("STT", "SPEECHKIT_STT"),
    ("TTS", "SPEECHKIT_TTS"),
    ("PTT", "UDP7082"),
    ("PROTECTED_OPERATIONAL_COMMUNICATION", "OSU"),
    ("PROTECTED_OPERATIONAL_COMMUNICATION", "PHRASEOLOGY"),
    ("VIRTUAL_ATC", "AIRPORT_ATC"),
    ("VIRTUAL_ATC", "CARRIER_ATC"),
    ("AIRPORT_ATC", "GROUND"),
    ("GROUND", "TAXI"),
    ("AIRPORT_ATC", "TOWER"),
    ("TOWER", "TAKEOFF"),
    ("TAKEOFF", "DEPARTURE"),
    ("AIRPORT_ATC", "ARRIVAL"),
    ("ARRIVAL", "APPROACH"),
    ("APPROACH", "LANDING"),
    ("APPROACH", "GO_AROUND"),
)

AREA_CAPABILITIES: dict[str, tuple[str, ...]] = {
    "Product": ("PRODUCT_SCOPE",),
    "Scope": ("PRODUCT_SCOPE", "RUNTIME_MODULES"),
    "ATC": ("VIRTUAL_ATC",),
    "Mission Control": ("MISSION_CONTROL",),
    "AWACS/GCI": ("AWACS_GCI",),
    "JTAC/FAC": ("JTAC_FAC",),
    "AAR": ("AAR",),
    "Aircraft Knowledge": ("AIRCRAFT_KNOWLEDGE",),
    "Debrief": ("DEBRIEF",),
    "Conversation": ("NATURAL_CONVERSATION",),
    "Current information": ("NEWS",),
    "Safety": ("SECURITY", "TOOL_CALLING"),
    "DCS data": ("DCS_TELEMETRY", "WORLD_MODEL"),
    "Callsign": ("CALLSIGN",),
    "Settings": ("LAUNCHER",),
    "Launcher": ("LAUNCHER",),
    "Installer": ("INSTALLER", "PACKAGING"),
    "Modules": ("RUNTIME_MODULES",),
    "Uninstall": ("UNINSTALLER",),
    "Audio": ("AUDIO_IO",),
    "Airport ATC": ("AIRPORT_ATC",),
    "Carrier ATC": ("CARRIER_ATC",),
    "Emergency": ("EMERGENCY",),
    "Mission editor": ("MISSION_EDITOR",),
    "Navigation": ("AIRCRAFT_KNOWLEDGE",),
    "Telemetry": ("DCS_TELEMETRY",),
    "Evidence": ("EVIDENCE",),
    "STT": ("STT",),
    "TTS": ("TTS",),
    "Voice boundary": ("STT", "LIFECYCLE"),
    "Lifecycle": ("LIFECYCLE",),
    "Qwen": ("QWEN_REALTIME", "QWEN_PLANNER"),
    "Qwen rollout": ("QWEN_REALTIME",),
    "Session": ("LIFECYCLE",),
    "Boundary": ("INTERACTION_ROUTING", "RADIO_ROUTER"),
    "Radio roles": ("RADIO_ENTITY", "SRS"),
    "SRS": ("SRS",),
    "Context": ("FLIGHT_CONTEXT", "LIVE_DCS_FACT_PRESENTATION"),
    "Privacy": ("SECURITY", "EVIDENCE"),
    "IA-0": ("INTERACTION_ROUTING",),
    "IA-1": ("PRESENTATION",),
    "IA-1.1": ("PRESENTATION", "SPEECHKIT_TTS"),
    "IA-2": ("WORLD_MODEL",),
    "IA-3": ("TOOL_CALLING",),
    "IA-4": ("REASONING",),
    "IA-5": ("QWEN_PLANNER",),
    "IA-6": ("INTERACTION_ROUTING",),
    "Language": ("LANGUAGE_POLICY",),
    "Profiles": ("COMMUNICATION_PROFILE", "LANGUAGE_POLICY"),
    "Phraseology": ("PHRASEOLOGY", "OSU"),
    "Packs": ("COMMUNICATION_PROFILE",),
    "Sources": ("COMMUNICATION_PROFILE",),
    "RadioEntity": ("RADIO_ENTITY", "VOICE_IDENTITY"),
    "Voice model": ("VOICE_IDENTITY",),
    "Radio": ("RADIO_ROUTER", "PTT", "EOU"),
    "Pilot KB": ("PHRASEOLOGY",),
    "Golden": ("OSU", "PROTECTED_OPERATIONAL_COMMUNICATION"),
    "Live Golden": ("MIXED_COMMUNICATION",),
    "PTT": ("PTT", "EOU", "UDP7082"),
    "MODEL C": ("INTERACTION_ROUTING", "PROTECTED_OPERATIONAL_COMMUNICATION"),
    "Profile UI": ("COMMUNICATION_PROFILE", "LAUNCHER"),
    "VR": ("VR_OVERLAY",),
    "Development process": ("ARCHITECTURE_GOVERNANCE",),
    "Informational UX": ("NATURAL_INFORMATIONAL_PRESENTATION",),
}

DECISION_CAPABILITY_OVERRIDES: dict[str, tuple[str, ...]] = {
    "D15": ("GENERAL_VR_TUNING", "LAUNCHER"),
    "D28": ("STT",),
    "D34": ("STT",),
    "D38": ("SRS",),
    "D39": ("SRS", "RADIO_SCHEDULING"),
    "D40": ("FLIGHT_CONTEXT", "LIVE_DCS_FACT_PRESENTATION", "NATURAL_INFORMATIONAL_PRESENTATION"),
    "D50": ("LANGUAGE_POLICY",),
    "D51": ("LANGUAGE_POLICY", "NATURAL_CONVERSATION", "PROTECTED_OPERATIONAL_COMMUNICATION"),
    "D52": ("COMMUNICATION_PROFILE",),
    "D54": ("PHRASEOLOGY", "MIXED_COMMUNICATION"),
    "D55": ("OSU", "PROTECTED_OPERATIONAL_COMMUNICATION"),
    "D56": ("COMMUNICATION_PROFILE",),
    "D62": ("PHRASEOLOGY", "MIXED_COMMUNICATION"),
    "D63": ("OSU", "PROTECTED_OPERATIONAL_COMMUNICATION"),
    "D65": ("STT", "SPEECHKIT_STT", "EOU"),
    "D66": ("PTT", "EOU", "UDP7082"),
    "D67": ("TTS", "SPEECHKIT_TTS", "RADIO_SCHEDULING"),
    "D68": ("INTERACTION_ROUTING", "TAKEOFF", "OSU"),
    "D69": ("COMMUNICATION_PROFILE", "LAUNCHER"),
    "D71": ("ARCHITECTURE_GOVERNANCE",),
    "D72": ("NATURAL_INFORMATIONAL_PRESENTATION", "PROTECTED_OPERATIONAL_COMMUNICATION"),
    "D73": ("ARCHITECTURE_GOVERNANCE",),
    "D74": ("ARCHITECTURE_GOVERNANCE", "PRODUCT_SCOPE"),
}

EVIDENCE_SEEDS: tuple[dict[str, Any], ...] = (
    {"id": "STAGE6A_FIELD_20260825", "name": "Stage 6A live DCS FlightContext field evidence", "item": "evidence:9a4812310edf7c3e0bd942b6c9f9508e778b35280d03759e2f84e3ff191c7162", "status": "FIELD_PROVEN", "confidence": "HIGH"},
    {"id": "AIRCRAFT_FA18_FIELD", "name": "F/A-18 live aircraft identity field evidence", "item": "evidence:987ced42e581a1e93aa7d7919732ee44e543d83cf2dc94318ad9d33eecdb21bb", "status": "FIELD_PROVEN", "confidence": "VERY_HIGH"},
    {"id": "AIRCRAFT_F5_FIELD", "name": "F-5 live aircraft identity field evidence", "item": "evidence:73a03e1dc1353486d646b445ff9a59dc6c875b9bb5dca59c651fed9886750e65", "status": "FIELD_PROVEN", "confidence": "VERY_HIGH"},
    {"id": "UDP7082_FIELD", "name": "UDP7082 authoritative PTT/EOU field evidence", "item": "evidence:8e9b25e187b9f80e0649750517e885755712779e898c9e223f8de5f68b33cc7a", "status": "FIELD_PROVEN", "confidence": "VERY_HIGH"},
    {"id": "SPEECHKIT_EXTERNAL_EOU_FIELD", "name": "SpeechKit external-EOU production path field evidence", "item": "evidence:bc1386e0d9e4bcd230d20018bf8c7099d289a6900e68313bcceec94ce79772dc", "status": "FIELD_PROVEN", "confidence": "VERY_HIGH"},
    {"id": "CADENCE_LIVENESS_FIELD", "name": "Cadence-aware long-PTT liveness field evidence", "item": "evidence:c211e07326cb1183b5b3cb68b6f70c2e1b5352bcfef08f500208cc14bd7664d8", "status": "FIELD_PROVEN", "confidence": "VERY_HIGH"},
    {"id": "PURE_TAKEOFF_FIELD", "name": "Pure takeoff MODEL C field evidence", "item": "evidence:f6248b2a386978b042aa3f2dacdaea199b439af3b292238af194718b5eb04788", "status": "FIELD_PROVEN", "confidence": "VERY_HIGH"},
    {"id": "PERSISTENT_ATC_FIELD", "name": "Persistent ATC session and status-query field evidence", "item": "evidence:90e21d8c5a67714ea9759de5200bbe3622eee0af9fd566e5f7851db0a4d1f93c", "status": "FIELD_PROVEN", "confidence": "VERY_HIGH"},
)

IMPLEMENTATION_SEEDS: tuple[dict[str, Any], ...] = (
    {
        "id": "STAGE6A_FLIGHTCONTEXT_REALTIME",
        "name": "Stage 6A/6A.1 FlightContext to persistent Yandex Realtime",
        "capabilities": ["AIRCRAFT_IDENTITY", "FLIGHT_CONTEXT", "LIVE_DCS_FACT_PRESENTATION", "NATURAL_INFORMATIONAL_PRESENTATION", "YANDEX_REALTIME"],
        "provider": "Yandex Realtime",
        "session_model": "PERSISTENT_REALTIME_SESSION",
        "runtime_status": "DISCONNECTED",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-08-25",
        "commits": ["f5c5d474e63261a16812cb0dfe23fb83f10ea180", "5896c4d961f502a4a59cbb31de3d533de8dfebe6"],
        "decisions": ["D40", "D72"],
        "evidence": ["STAGE6A_FIELD_20260825"],
        "mechanisms": ["PERSISTENT_REALTIME_SESSION", "FLIGHTCONTEXT_UPDATE_GATE"],
        "files": ["orion/flight_context.py", "orion/yandex_realtime.py"],
        "strengths": ["live DCS facts injected into a persistent conversational session", "natural informational formulation"],
        "defects": ["historical implementation is not the current aircraft query route"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "CURRENT_AIRCRAFT_IDENTITY_QUERY",
        "name": "Current AIRCRAFT_IDENTITY_QUERY with Core fact binding",
        "capabilities": ["AIRCRAFT_IDENTITY", "WORLD_MODEL", "LIVE_DCS_FACT_PRESENTATION", "NATURAL_INFORMATIONAL_PRESENTATION", "SPEECHKIT_TTS", "SRS"],
        "provider": "Qwen Planner + SpeechKit TTS",
        "session_model": "BOUNDED_INFORMATIONAL_QUERY",
        "runtime_status": "CURRENT",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-09-02",
        "commits": ["27e94bdbf843a3f1895db2756eed49e42fe07989"],
        "decisions": ["D45", "D47", "D48", "D72"],
        "evidence": ["AIRCRAFT_FA18_FIELD", "AIRCRAFT_F5_FIELD"],
        "mechanisms": ["CORE_FACT_BINDING", "PLACEHOLDER_FACT_VALIDATION"],
        "files": ["orion/aircraft_identity_query.py"],
        "strengths": ["Core-owned live fact and provenance", "natural formulation with exact post-validation substitution"],
        "defects": ["bounded to the implemented aircraft identity contract"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "CURRENT_QWEN_INFORMATIONAL_FORMULATION",
        "name": "Qwen Planner natural informational formulation",
        "capabilities": ["QWEN_PLANNER", "REASONING", "NATURAL_INFORMATIONAL_PRESENTATION"],
        "provider": "Yandex Qwen",
        "session_model": "BOUNDED_PLANNER_CALL",
        "runtime_status": "CURRENT",
        "historical_status": "IMPLEMENTED",
        "introduced_at": "2026-08-27",
        "commits": ["a4f9942"],
        "decisions": ["D47", "D48", "D72"],
        "evidence": ["AIRCRAFT_FA18_FIELD", "AIRCRAFT_F5_FIELD"],
        "mechanisms": ["PLACEHOLDER_FACT_VALIDATION"],
        "files": ["orion/yandex_qwen_planner.py", "orion/aircraft_identity_query.py"],
        "strengths": ["provider-neutral Planner contract", "natural wording without fact authority"],
        "defects": [],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "PACKET_GAP_EOU_HEURISTIC",
        "name": "Packet-gap/quiescence radio EOU heuristic",
        "capabilities": ["PTT", "EOU", "RADIO_SCHEDULING"],
        "runtime_status": "SUPERSEDED",
        "historical_status": "SUPERSEDED",
        "introduced_at": "2026-08-28",
        "decisions": ["D66"],
        "mechanisms": ["PACKET_GAP_EOU"],
        "strengths": ["bounded heuristic before authoritative TX state existed"],
        "defects": ["could finalize before a physical PTT transmission ended"],
        "abandonment_reason": "FIELD_FAILURE",
    },
    {
        "id": "UDP7082_AUTHORITATIVE_EOU",
        "name": "Official SRS UDP7082 authoritative local TX end",
        "capabilities": ["PTT", "EOU", "UDP7082", "SRS"],
        "runtime_status": "CURRENT",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-08-31",
        "commits": ["55e70f83c839ef2f3a375167785c33feca2a9125"],
        "decisions": ["D66"],
        "evidence": ["UDP7082_FIELD"],
        "mechanisms": ["UDP7082_TRUE_FALSE_EOU", "SRS_CANDIDATE_BUFFERING"],
        "strengths": ["physical PTT true-to-false transition owns end of transmission"],
        "defects": ["requires cadence-aware liveness for repeated true snapshots"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "SRS_CANDIDATE_BUFFERING_IMPLEMENTATION",
        "name": "SRS candidate PCM ownership and buffering",
        "capabilities": ["PTT", "EOU", "SRS", "RADIO_SCHEDULING"],
        "runtime_status": "CURRENT",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-08-31",
        "commits": ["43c364a"],
        "decisions": ["D65", "D66"],
        "evidence": ["SPEECHKIT_EXTERNAL_EOU_FIELD"],
        "mechanisms": ["SRS_CANDIDATE_BUFFERING", "SPEECHKIT_EXTERNAL_EOU"],
        "strengths": ["false-only traffic cannot become a local turn", "PCM is held until authoritative ownership"],
        "defects": ["fixed stale timing was sensitive to sender cadence"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "CADENCE_AWARE_TX_LIVENESS_IMPLEMENTATION",
        "name": "Cadence-aware UDP7082 TX-state liveness",
        "capabilities": ["PTT", "EOU", "UDP7082", "RADIO_SCHEDULING"],
        "runtime_status": "CURRENT",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-09-01",
        "commits": ["5cc976a26b12be0520d560cda88ac47fbd1cda4b"],
        "decisions": ["D66"],
        "evidence": ["CADENCE_LIVENESS_FIELD"],
        "mechanisms": ["CADENCE_AWARE_TX_LIVENESS", "UDP7082_TRUE_FALSE_EOU"],
        "strengths": ["long physical PTT survives expected sender cadence"],
        "defects": [],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "HARD_FOUR_LANGUAGE_MODES",
        "name": "Four hard FREE/AVIATION RU/EN modes",
        "capabilities": ["LANGUAGE_POLICY"],
        "runtime_status": "HISTORICAL_ONLY",
        "historical_status": "SUPERSEDED",
        "introduced_at": "2026-08-27",
        "decisions": ["D50", "D51", "D52"],
        "strengths": ["simple initial mode model"],
        "defects": ["conflated input language, conversational language and aviation procedure profile"],
        "abandonment_reason": "USER_REJECTED",
    },
    {
        "id": "AUTOMATIC_INPUT_LANGUAGE_POLICY",
        "name": "Any-supported-input and follow-user conversational language policy",
        "capabilities": ["LANGUAGE_POLICY", "NATURAL_CONVERSATION"],
        "runtime_status": "CURRENT",
        "historical_status": "IMPLEMENTED",
        "introduced_at": "2026-08-27",
        "commits": ["f1a3e08"],
        "decisions": ["D51", "D53"],
        "files": ["orion/communication_contracts.py"],
        "strengths": ["separates user language from operational communication profile"],
        "defects": ["runtime coverage remains bounded by implemented routes"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "COMMUNICATION_PROFILE_INFRASTRUCTURE",
        "name": "Communication Profile selection and pack lifecycle",
        "capabilities": ["COMMUNICATION_PROFILE", "LANGUAGE_POLICY", "PHRASEOLOGY", "LAUNCHER"],
        "runtime_status": "CURRENT",
        "historical_status": "AUTOMATED_PROVEN",
        "introduced_at": "2026-09-01",
        "commits": ["01a499e"],
        "decisions": ["D52", "D53", "D56", "D57", "D69"],
        "mechanisms": ["COMMUNICATION_PROFILE_PACK_LIFECYCLE"],
        "files": ["orion/communication_profile_packs.py", "orion/communication_profile_api.py", "orion/launcher_communication_profiles.py"],
        "strengths": ["persisted profile IDs and active/candidate/previous-known-good lifecycle", "truth/provider/permission isolation"],
        "defects": ["verified normative profile content is not yet installed"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "WHISPER_STT_WORKER",
        "name": "Legacy local Whisper/ORION-Voice STT worker",
        "capabilities": ["STT", "AUDIO_IO", "LIFECYCLE"],
        "runtime_status": "EXPLICITLY_REMOVED",
        "historical_status": "EXPLICITLY_REMOVED",
        "introduced_at": "2026-08-14",
        "commits": ["1963c60f0f4969cf05857d840bbaeb5bd4520250"],
        "decisions": ["D28", "D30", "D34"],
        "strengths": ["local speech recognition path"],
        "defects": ["separate worker and local dependency footprint"],
        "abandonment_reason": "DEPENDENCY_REMOVAL",
    },
    {
        "id": "SPEECHKIT_V3_EXTERNAL_EOU_STT",
        "name": "SpeechKit v3 RecognizeStreaming External-EOU radio STT",
        "capabilities": ["STT", "SPEECHKIT_STT", "PTT", "EOU", "SRS"],
        "provider": "Yandex SpeechKit",
        "session_model": "PERSISTENT_MULTI_PTT_RPC",
        "runtime_status": "CURRENT",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-08-31",
        "commits": ["255f200"],
        "decisions": ["D65", "D66"],
        "evidence": ["SPEECHKIT_EXTERNAL_EOU_FIELD"],
        "mechanisms": ["SPEECHKIT_EXTERNAL_EOU", "SRS_CANDIDATE_BUFFERING"],
        "strengths": ["complete PCM plus one explicit Eou and native final/cursor barrier", "persistent multi-turn session"],
        "defects": [],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "PILOT_PHRASEOLOGY_TEST_CORPUS",
        "name": "Pilot Phraseology bounded mixed-composition test corpus",
        "capabilities": ["PHRASEOLOGY", "MIXED_COMMUNICATION"],
        "runtime_status": "DISCONNECTED",
        "historical_status": "PROBE_PROVEN",
        "introduced_at": "2026-08-28",
        "commits": ["a85ab98"],
        "decisions": ["D62"],
        "strengths": ["bounded deterministic rendering and mixed-composition validation"],
        "defects": ["not a production KB size or full intent taxonomy"],
        "abandonment_reason": "TEMPORARY_EXPERIMENT",
        "metadata": {"kb_scope": "TEST_CORPUS_ONLY"},
    },
    {
        "id": "PILOT_20_30_PRODUCT_KB_INTERPRETATION",
        "name": "Rejected interpretation of 20-30 as production KB scope",
        "capabilities": ["PHRASEOLOGY"],
        "runtime_status": "HISTORICAL_ONLY",
        "historical_status": "HISTORICAL_ONLY",
        "introduced_at": "2026-08-28",
        "decisions": ["D62"],
        "strengths": [],
        "defects": ["contradicts the explicit test-corpus-only clarification"],
        "abandonment_reason": "USER_REJECTED",
        "metadata": {"interpretation": "REJECTED", "kb_scope": "NOT_PRODUCT"},
    },
    {
        "id": "OSU_PROTECTED_PHRASEOLOGY",
        "name": "Core-owned OSU protected operational presentation",
        "capabilities": ["OSU", "PHRASEOLOGY", "PROTECTED_OPERATIONAL_COMMUNICATION"],
        "runtime_status": "CURRENT",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-08-28",
        "commits": ["9f38d44", "6f6f2f1"],
        "decisions": ["D54", "D55", "D63", "D68", "D72"],
        "evidence": ["PURE_TAKEOFF_FIELD"],
        "mechanisms": ["OSU_PROTECTED_PRESENTATION", "DETERMINISTIC_KNOWN_CONTRACT"],
        "strengths": ["protected fragment never returns to Qwen", "Core owns verified operational wording"],
        "defects": ["coverage is bounded to migrated contracts"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "PURE_TAKEOFF_MODEL_C",
        "name": "Pure takeoff deterministic MODEL C route",
        "capabilities": ["INTERACTION_ROUTING", "TAKEOFF", "VIRTUAL_ATC", "OSU", "PHRASEOLOGY"],
        "runtime_status": "CURRENT",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-09-01",
        "commits": ["6f6f2f1aebbbde36aa0f0860df265c1e6013fd7b"],
        "decisions": ["D63", "D68"],
        "evidence": ["PURE_TAKEOFF_FIELD"],
        "mechanisms": ["DETERMINISTIC_KNOWN_CONTRACT", "OSU_PROTECTED_PRESENTATION"],
        "strengths": ["safely recognized pure request bypasses Qwen", "Core truth and protected wording"],
        "defects": ["only the bounded pure takeoff contract is migrated"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "PERSISTENT_ATC_SESSION_IMPLEMENTATION",
        "name": "Persistent Core ATC session",
        "capabilities": ["VIRTUAL_ATC", "ATC_STATUS", "TAKEOFF", "PERSISTENT_STATE"],
        "runtime_status": "CURRENT",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-09-01",
        "commits": ["6dea803e9deac09d0ed9e59d7b60cb6368a7a83e"],
        "decisions": ["D03", "D21", "D68"],
        "evidence": ["PERSISTENT_ATC_FIELD"],
        "mechanisms": ["PERSISTENT_ATC_SESSION", "DETERMINISTIC_KNOWN_CONTRACT"],
        "strengths": ["multiple PTT turns bind to one Core-owned ATC state"],
        "defects": ["full live-DCS ATC lifecycle remains incomplete"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "ATC_STATUS_QUERY_IMPLEMENTATION",
        "name": "Bounded deterministic ATC_STATUS_QUERY",
        "capabilities": ["VIRTUAL_ATC", "ATC_STATUS", "INTERACTION_ROUTING"],
        "runtime_status": "CURRENT",
        "historical_status": "FIELD_PROVEN",
        "introduced_at": "2026-09-01",
        "commits": ["6dea803e9deac09d0ed9e59d7b60cb6368a7a83e"],
        "decisions": ["D03", "D68"],
        "evidence": ["PERSISTENT_ATC_FIELD"],
        "mechanisms": ["PERSISTENT_ATC_SESSION", "DETERMINISTIC_KNOWN_CONTRACT"],
        "strengths": ["reads the same persistent ATC session with zero Qwen calls"],
        "defects": ["bounded status-query contract"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "INTERACTION_ROUTER_IA6",
        "name": "IA-6 bounded InteractionRouter",
        "capabilities": ["INTERACTION_ROUTING", "REASONING", "TOOL_CALLING"],
        "runtime_status": "CURRENT",
        "historical_status": "IMPLEMENTED",
        "introduced_at": "2026-08-27",
        "commits": ["f1a3e08"],
        "decisions": ["D49"],
        "files": ["orion/interaction_router.py"],
        "strengths": ["provider-neutral routing seam"],
        "defects": ["initial slice was intentionally narrow"],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "CORE_TOOL_GATEWAY",
        "name": "Core-governed typed ToolGateway",
        "capabilities": ["TOOL_CALLING", "SECURITY", "WORLD_MODEL"],
        "runtime_status": "CURRENT",
        "historical_status": "IMPLEMENTED",
        "introduced_at": "2026-08-27",
        "commits": ["913b8b8"],
        "decisions": ["D46"],
        "files": ["orion/tool_gateway.py"],
        "strengths": ["Core owns permissions and typed tool boundary"],
        "defects": [],
        "abandonment_reason": "UNKNOWN",
    },
    {
        "id": "RADIO_ENTITY_VOICE_PROBE",
        "name": "Persistent radio-entity voice probe",
        "capabilities": ["RADIO_ENTITY", "VOICE_IDENTITY"],
        "runtime_status": "DISCONNECTED",
        "historical_status": "IMPLEMENTED",
        "introduced_at": "2026-08-27",
        "decisions": ["D58", "D59"],
        "strengths": ["models recognizable voice per radio entity"],
        "defects": ["not production-wired"],
        "abandonment_reason": "UNKNOWN",
    },
)

MECHANISM_SEEDS: tuple[dict[str, Any], ...] = (
    {"id": "PERSISTENT_REALTIME_SESSION", "description": "Keep one Realtime session alive across context updates.", "invariant": "Context updates do not require a new provider session.", "capabilities": ["YANDEX_REALTIME", "NATURAL_INFORMATIONAL_PRESENTATION"], "current": True, "status": "FIELD_PROVEN", "refs": ["D40", "f5c5d474e63261a16812cb0dfe23fb83f10ea180"]},
    {"id": "FLIGHTCONTEXT_UPDATE_GATE", "description": "Inject only materially changed, bounded FlightContext.", "invariant": "Authoritative telemetry cadence remains Core-owned.", "capabilities": ["FLIGHT_CONTEXT", "LIVE_DCS_FACT_PRESENTATION"], "current": True, "status": "FIELD_PROVEN", "refs": ["D40", "5896c4d961f502a4a59cbb31de3d533de8dfebe6"]},
    {"id": "CORE_FACT_BINDING", "description": "Core binds the exact authoritative fact after AI wording validation.", "invariant": "AI cannot replace, infer, or override the Core fact.", "capabilities": ["AIRCRAFT_IDENTITY", "LIVE_DCS_FACT_PRESENTATION"], "current": True, "status": "FIELD_PROVEN", "refs": ["D72", "27e94bdbf843a3f1895db2756eed49e42fe07989"]},
    {"id": "PLACEHOLDER_FACT_VALIDATION", "description": "Validate a bounded sentence shell and substitute the fact in Core.", "invariant": "Exactly one approved placeholder; no added aircraft or numeric facts.", "capabilities": ["AIRCRAFT_IDENTITY", "NATURAL_INFORMATIONAL_PRESENTATION", "QWEN_PLANNER"], "current": True, "status": "FIELD_PROVEN", "refs": ["D72", "27e94bdbf843a3f1895db2756eed49e42fe07989"]},
    {"id": "DETERMINISTIC_KNOWN_CONTRACT", "description": "Recognize a bounded pure contract before Planner routing.", "invariant": "Safely recognized protected operational requests bypass Qwen.", "capabilities": ["INTERACTION_ROUTING", "PROTECTED_OPERATIONAL_COMMUNICATION"], "current": True, "status": "FIELD_PROVEN", "refs": ["D68", "6f6f2f1aebbbde36aa0f0860df265c1e6013fd7b"]},
    {"id": "OSU_PROTECTED_PRESENTATION", "description": "Render protected OperationalSemanticUnit wording in Core.", "invariant": "Protected operational fragments never return to Qwen.", "capabilities": ["OSU", "PHRASEOLOGY", "PROTECTED_OPERATIONAL_COMMUNICATION"], "current": True, "status": "FIELD_PROVEN", "refs": ["D55", "D63", "6f6f2f1aebbbde36aa0f0860df265c1e6013fd7b"]},
    {"id": "SPEECHKIT_EXTERNAL_EOU", "description": "Send complete PCM then exactly one explicit SpeechKit Eou.", "invariant": "Native FINAL and EOU_UPDATE cursor barrier finalize the turn.", "capabilities": ["SPEECHKIT_STT", "EOU"], "current": True, "status": "FIELD_PROVEN", "refs": ["D65", "255f200"]},
    {"id": "UDP7082_TRUE_FALSE_EOU", "description": "Use official SRS IsSending true-to-false as physical TX end.", "invariant": "Packet silence is not authoritative EOU.", "capabilities": ["PTT", "EOU", "UDP7082"], "current": True, "status": "FIELD_PROVEN", "refs": ["D66", "55e70f83c839ef2f3a375167785c33feca2a9125"]},
    {"id": "PACKET_GAP_EOU", "description": "Historical packet-quiescence EOU heuristic.", "invariant": "Superseded; must not own physical PTT end.", "capabilities": ["PTT", "EOU"], "current": False, "status": "SUPERSEDED", "refs": ["D66"], "defects": ["could finalize before the physical PTT transmission ended"]},
    {"id": "SRS_CANDIDATE_BUFFERING", "description": "Buffer candidate PCM until local TX ownership is established.", "invariant": "False-only incoming traffic cannot become a local SpeechKit turn.", "capabilities": ["SRS", "PTT", "RADIO_SCHEDULING"], "current": True, "status": "FIELD_PROVEN", "refs": ["D65", "D66", "43c364a"]},
    {"id": "FIXED_TIMEOUT_TX_LIVENESS", "description": "Historical fixed stale timeout for repeated TX-state snapshots.", "invariant": "Superseded by cadence-aware liveness.", "capabilities": ["UDP7082", "RADIO_SCHEDULING"], "current": False, "status": "SUPERSEDED", "refs": ["5cc976a26b12be0520d560cda88ac47fbd1cda4b"], "defects": ["could mark valid sparse repeated sender snapshots stale"]},
    {"id": "CADENCE_AWARE_TX_LIVENESS", "description": "Evaluate repeated IsSending snapshots against observed sender cadence.", "invariant": "A long valid PTT does not become stale between expected snapshots.", "capabilities": ["PTT", "UDP7082", "RADIO_SCHEDULING"], "current": True, "status": "FIELD_PROVEN", "refs": ["D66", "5cc976a26b12be0520d560cda88ac47fbd1cda4b"]},
    {"id": "STREAMING_TTS", "description": "Stream SpeechKit synthesis into one bounded SRS TX lifecycle.", "invariant": "One finalized response produces one paced radio transmission.", "capabilities": ["SPEECHKIT_TTS", "RADIO_SCHEDULING", "SRS"], "current": True, "status": "FIELD_PROVEN", "refs": ["D67", "0902710"]},
    {"id": "RADIO_ROUTER", "description": "Provider-neutral routing from semantic audio output to radio transport.", "invariant": "AI provider and transport remain independent axes.", "capabilities": ["RADIO_ROUTER", "SRS"], "current": True, "status": "FIELD_PROVEN", "refs": ["D36", "D60", "49f083d"]},
    {"id": "RADIO_ENTITY", "description": "Stable radio role/entity identity and voice profile seam.", "invariant": "Identity is separate from provider and transport.", "capabilities": ["RADIO_ENTITY", "VOICE_IDENTITY"], "current": False, "status": "DISCONNECTED", "refs": ["D58", "D59"], "defects": ["not production-wired"]},
    {"id": "COMMUNICATION_PROFILE_PACK_LIFECYCLE", "description": "Versioned active/candidate/previous-known-good local profile packs.", "invariant": "Profile presentation cannot alter truth, permissions, provider, or mission state.", "capabilities": ["COMMUNICATION_PROFILE", "PHRASEOLOGY", "LANGUAGE_POLICY"], "current": True, "status": "AUTOMATED_PROVEN", "refs": ["D53", "D56", "01a499e"]},
    {"id": "PERSISTENT_ATC_SESSION", "description": "Retain Core-owned ATC state across sequential physical PTT turns.", "invariant": "Status queries read the same authoritative ATC session.", "capabilities": ["VIRTUAL_ATC", "ATC_STATUS", "TAKEOFF"], "current": True, "status": "FIELD_PROVEN", "refs": ["D03", "D21", "6dea803e9deac09d0ed9e59d7b60cb6368a7a83e"]},
)

EXTRA_RELATIONSHIPS: tuple[dict[str, Any], ...] = (
    {"source": ("IMPLEMENTATION", "STAGE6A_FLIGHTCONTEXT_REALTIME"), "type": "RELATES_TO", "target": ("IMPLEMENTATION", "CURRENT_AIRCRAFT_IDENTITY_QUERY"), "refs": ["D40", "D72", "27e94bdbf843a3f1895db2756eed49e42fe07989"], "confidence": "VERY_HIGH", "metadata": {"same_capability_not_same_implementation": True}},
    {"source": ("IMPLEMENTATION", "PACKET_GAP_EOU_HEURISTIC"), "type": "REPLACED_BY", "target": ("IMPLEMENTATION", "UDP7082_AUTHORITATIVE_EOU"), "refs": ["D66", "55e70f83c839ef2f3a375167785c33feca2a9125"], "confidence": "VERY_HIGH"},
    {"source": ("MECHANISM", "UDP7082_TRUE_FALSE_EOU"), "type": "SUPERSEDES", "target": ("MECHANISM", "PACKET_GAP_EOU"), "refs": ["D66"], "confidence": "VERY_HIGH"},
    {"source": ("MECHANISM", "CADENCE_AWARE_TX_LIVENESS"), "type": "SUPERSEDES", "target": ("MECHANISM", "FIXED_TIMEOUT_TX_LIVENESS"), "refs": ["5cc976a26b12be0520d560cda88ac47fbd1cda4b"], "confidence": "VERY_HIGH"},
    {"source": ("IMPLEMENTATION", "SRS_CANDIDATE_BUFFERING_IMPLEMENTATION"), "type": "DEPENDS_ON", "target": ("IMPLEMENTATION", "UDP7082_AUTHORITATIVE_EOU"), "refs": ["D65", "D66", "43c364a"], "confidence": "VERY_HIGH"},
    {"source": ("IMPLEMENTATION", "CADENCE_AWARE_TX_LIVENESS_IMPLEMENTATION"), "type": "REUSES_MECHANISM", "target": ("MECHANISM", "SRS_CANDIDATE_BUFFERING"), "refs": ["D66", "5cc976a26b12be0520d560cda88ac47fbd1cda4b"], "confidence": "HIGH"},
    {"source": ("IMPLEMENTATION", "AUTOMATIC_INPUT_LANGUAGE_POLICY"), "type": "SUPERSEDES", "target": ("IMPLEMENTATION", "HARD_FOUR_LANGUAGE_MODES"), "refs": ["D50", "D51"], "confidence": "VERY_HIGH"},
    {"source": ("IMPLEMENTATION", "COMMUNICATION_PROFILE_INFRASTRUCTURE"), "type": "DEPENDS_ON", "target": ("IMPLEMENTATION", "AUTOMATIC_INPUT_LANGUAGE_POLICY"), "refs": ["D51", "D52", "D53"], "confidence": "VERY_HIGH"},
    {"source": ("DECISION", "D34"), "type": "REJECTS", "target": ("IMPLEMENTATION", "WHISPER_STT_WORKER"), "refs": ["D34", "1963c60f0f4969cf05857d840bbaeb5bd4520250"], "confidence": "VERY_HIGH"},
    {"source": ("DECISION", "D62"), "type": "REJECTS", "target": ("IMPLEMENTATION", "PILOT_20_30_PRODUCT_KB_INTERPRETATION"), "refs": ["D62"], "confidence": "VERY_HIGH"},
    {"source": ("IMPLEMENTATION", "OSU_PROTECTED_PHRASEOLOGY"), "type": "RELATES_TO", "target": ("IMPLEMENTATION", "PILOT_PHRASEOLOGY_TEST_CORPUS"), "refs": ["D54", "D55", "D62", "D63"], "confidence": "VERY_HIGH", "metadata": {"test_corpus_is_not_product_scope": True}},
    {"source": ("IMPLEMENTATION", "PERSISTENT_ATC_SESSION_IMPLEMENTATION"), "type": "DEPENDS_ON", "target": ("IMPLEMENTATION", "PURE_TAKEOFF_MODEL_C"), "refs": ["D68", "6dea803e9deac09d0ed9e59d7b60cb6368a7a83e"], "confidence": "HIGH"},
    {"source": ("IMPLEMENTATION", "ATC_STATUS_QUERY_IMPLEMENTATION"), "type": "USES", "target": ("MECHANISM", "PERSISTENT_ATC_SESSION"), "refs": ["6dea803e9deac09d0ed9e59d7b60cb6368a7a83e"], "confidence": "VERY_HIGH"},
    {"source": ("DECISION", "D15"), "type": "REJECTS", "target": ("CAPABILITY", "GENERAL_VR_TUNING"), "refs": ["D15"], "confidence": "VERY_HIGH"},
)

OWNERSHIP_SEEDS: tuple[dict[str, Any], ...] = (
    {"role": "FACT_AUTHORITY", "owner": ("IMPLEMENTATION", "CURRENT_AIRCRAFT_IDENTITY_QUERY"), "capability": "AIRCRAFT_IDENTITY", "status": "CURRENT", "refs": ["D45", "D72", "27e94bdbf843a3f1895db2756eed49e42fe07989"]},
    {"role": "SEMANTIC_INTERPRETATION", "owner": ("IMPLEMENTATION", "INTERACTION_ROUTER_IA6"), "capability": "INTERACTION_ROUTING", "status": "CURRENT", "refs": ["D49", "f1a3e08"]},
    {"role": "REASONING", "owner": ("IMPLEMENTATION", "CURRENT_QWEN_INFORMATIONAL_FORMULATION"), "capability": "REASONING", "status": "CURRENT_BOUNDED", "refs": ["D47", "D48", "D72"]},
    {"role": "TOOL_PERMISSION", "owner": ("IMPLEMENTATION", "CORE_TOOL_GATEWAY"), "capability": "TOOL_CALLING", "status": "CURRENT", "refs": ["D46", "913b8b8"]},
    {"role": "NATURAL_INFORMATIONAL_WORDING", "owner": ("IMPLEMENTATION", "CURRENT_QWEN_INFORMATIONAL_FORMULATION"), "capability": "NATURAL_INFORMATIONAL_PRESENTATION", "status": "CURRENT", "refs": ["D72", "27e94bdbf843a3f1895db2756eed49e42fe07989"]},
    {"role": "PROTECTED_OPERATIONAL_WORDING", "owner": ("MECHANISM", "OSU_PROTECTED_PRESENTATION"), "capability": "PROTECTED_OPERATIONAL_COMMUNICATION", "status": "CURRENT", "refs": ["D55", "D63", "D72"]},
    {"role": "PHRASEOLOGY", "owner": ("MECHANISM", "OSU_PROTECTED_PRESENTATION"), "capability": "PHRASEOLOGY", "status": "CURRENT_BOUNDED", "refs": ["D54", "D55", "D63"]},
    {"role": "STT", "owner": ("IMPLEMENTATION", "SPEECHKIT_V3_EXTERNAL_EOU_STT"), "capability": "SPEECHKIT_STT", "status": "CURRENT_OPTION", "refs": ["D65"]},
    {"role": "TTS", "owner": ("MECHANISM", "STREAMING_TTS"), "capability": "SPEECHKIT_TTS", "status": "CURRENT_PRIMARY", "refs": ["D67"]},
    {"role": "VOICE_IDENTITY", "owner": ("MECHANISM", "RADIO_ENTITY"), "capability": "VOICE_IDENTITY", "status": "DISCONNECTED", "refs": ["D58", "D59"]},
    {"role": "RADIO_TRANSPORT", "owner": ("MECHANISM", "RADIO_ROUTER"), "capability": "RADIO_ROUTER", "status": "CURRENT", "refs": ["D36", "D60", "D61"]},
    {"role": "PHYSICAL_PTT", "owner": ("MECHANISM", "UDP7082_TRUE_FALSE_EOU"), "capability": "PTT", "status": "CURRENT", "refs": ["D66"]},
    {"role": "EOU", "owner": ("MECHANISM", "UDP7082_TRUE_FALSE_EOU"), "capability": "EOU", "status": "CURRENT_PHYSICAL_END", "refs": ["D66"]},
    {"role": "PERSISTENT_STATE", "owner": ("MECHANISM", "PERSISTENT_ATC_SESSION"), "capability": "VIRTUAL_ATC", "status": "CURRENT_BOUNDED", "refs": ["D03", "D21", "6dea803e9deac09d0ed9e59d7b60cb6368a7a83e"]},
    {"role": "LIFECYCLE", "owner": ("IMPLEMENTATION", "INTERACTION_ROUTER_IA6"), "capability": "LIFECYCLE", "status": "PARTIAL_SCOPE", "refs": ["D31", "D35", "D49"]},
)
